name: Build

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: true

jobs:    
  linux-musl:
    name: build emotion-swc-plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Install wasi
        run: rustup target add wasm32-wasi
      - name: Build
        run: |
          rustup -V
          rustup toolchain list
          cargo -V
          cd emotion-swc-plugin
          cargo build --release
      - name: github publish
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.event.inputs.tag }}
          draft: true
          bodyFile: target/wasm32-wasi/release/emotion-swc-plugin.wasm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: npm publish emotion-swc-plugin
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}