name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: true

jobs:    
  linux-musl:
    name: build emotion-swc-plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Install wasi
        run: rustup target add wasm32-wasi

      - name: Run test
        run: cargo test --color always

      - name: Build
        run: |
          rustup -V
          rustup toolchain list
          cargo -V
          cargo build --release

      - name: Increment version
        run: npm --no-git-tag-version version ${{ github.event.inputs.tag }}
        
      - name: npm publish emotion-swc-plugin
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
